# Generated by Django 5.1.5 on 2025-02-02 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_dept', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='description',
            new_name='department_description',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='dept_name',
            new_name='department_name',
        ),
    ]
