# Generated by Django 5.1.5 on 2025-02-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_dept', '0002_rename_description_department_department_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='status',
            field=models.BooleanField(default='True', max_length=50),
        ),
    ]
